# Generated by Django 2.2.11 on 2020-06-29 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=70)),
                ('department_date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=70)),
                ('position_date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('surname', models.CharField(blank=True, max_length=100)),
                ('fathers_name', models.CharField(blank=True, max_length=100)),
                ('birthday', models.DateField(blank=True)),
                ('icq', models.CharField(blank=True, max_length=30)),
                ('skype', models.CharField(blank=True, max_length=30)),
                ('prone_number_job', models.CharField(blank=True, max_length=30)),
                ('prone_number_home', models.CharField(blank=True, max_length=30)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Department')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Position')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
