# Generated by Django 2.2.11 on 2020-06-29 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200629_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Department'),
        ),
    ]
