# Generated by Django 2.2.11 on 2020-06-29 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200629_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Position'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='prone_number_home',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='prone_number_job',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
