# Generated by Django 2.2.11 on 2020-06-29 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20200629_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='prone_number_home',
            new_name='phone_number_home',
        ),
        migrations.RenameField(
            model_name='profiles',
            old_name='prone_number_job',
            new_name='phone_number_job',
        ),
    ]
