# Generated by Django 2.2.11 on 2020-06-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profiles_work_is_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='avatar',
            field=models.ImageField(default=None, upload_to='media/images'),
        ),
    ]
