# Generated by Django 2.2.11 on 2020-06-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20200629_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='name',
            field=models.CharField(blank=True, default='Новый пользователь, добавьте информацию в профиль', max_length=100),
        ),
    ]
