# Generated by Django 2.2.11 on 2020-06-30 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20200630_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='name',
            field=models.CharField(blank=True, default=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), max_length=100),
        ),
    ]
