# Generated by Django 2.2.11 on 2020-07-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20200630_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
