# Generated by Django 3.0.7 on 2020-07-11 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0033_auto_20200711_1330'),
        ('profiles', '0016_profiles_only_their_courts'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='observer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courts.Courts', verbose_name='Ответственный'),
        ),
    ]
