# Generated by Django 3.0.7 on 2020-07-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0033_auto_20200711_1330'),
        ('profiles', '0017_profiles_observer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='observer',
        ),
        migrations.AddField(
            model_name='profiles',
            name='observer',
            field=models.ManyToManyField(blank=True, null=True, related_name='_profiles_observer_+', to='courts.Courts', verbose_name='Ответственный'),
        ),
    ]
