# Generated by Django 3.0.7 on 2020-07-11 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_auto_20200711_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='observer',
        ),
    ]
