# Generated by Django 3.0.7 on 2020-07-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_remove_profiles_observer'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='only_courts_where_im_is_observer',
            field=models.BooleanField(default=False),
        ),
    ]
