# Generated by Django 3.0.7 on 2020-07-12 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_profiles_only_courts_where_im_is_observer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='only_courts_where_im_is_observer',
        ),
    ]
