# Generated by Django 2.2.11 on 2020-07-15 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_remove_profiles_only_courts_where_im_is_observer'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='courts_common_jurisdiction',
            field=models.BooleanField(default=False),
        ),
    ]
