# Generated by Django 3.1 on 2020-09-04 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_auto_20200904_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mysession',
            name='active',
        ),
        migrations.RemoveField(
            model_name='mysession',
            name='expire_date',
        ),
        migrations.RemoveField(
            model_name='mysession',
            name='name_board',
        ),
        migrations.RemoveField(
            model_name='mysession',
            name='thread',
        ),
        migrations.AlterField(
            model_name='mysession',
            name='user',
            field=models.IntegerField(),
        ),
    ]
