# Generated by Django 3.1 on 2020-09-04 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('profiles', '0026_auto_20200904_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysession',
            name='session_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions.session'),
        ),
    ]
