# Generated by Django 3.1 on 2020-09-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0047_auto_20200820_1814'),
        ('profiles', '0032_auto_20200922_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='read_courts',
            field=models.ManyToManyField(to='courts.Courts'),
        ),
    ]
