# Generated by Django 3.1 on 2020-09-23 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0033_profiles_read_courts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='read_courts',
        ),
    ]
