# Generated by Django 3.1 on 2020-09-23 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0047_auto_20200820_1814'),
        ('profiles', '0035_profiles_read_courts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='read_courts',
        ),
        migrations.AddField(
            model_name='profiles',
            name='unread_courts',
            field=models.ManyToManyField(default=True, to='courts.Courts'),
        ),
    ]
