# Generated by Django 3.1 on 2020-09-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0047_auto_20200820_1814'),
        ('profiles', '0036_auto_20200923_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='unread_courts',
            field=models.ManyToManyField(blank=True, null=True, to='courts.Courts'),
        ),
    ]
