# Generated by Django 3.1 on 2020-09-28 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0037_auto_20200923_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='unread_courts',
        ),
    ]
