# Generated by Django 2.2.11 on 2020-07-16 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0035_auto_20200711_1430'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('execution', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executions',
            name='title',
        ),
        migrations.AddField(
            model_name='executions',
            name='agency',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Наименование органа исполнения'),
        ),
        migrations.AddField(
            model_name='executions',
            name='agency_address',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Адрес (местонахождение) органа исполнения'),
        ),
        migrations.AddField(
            model_name='executions',
            name='arhive',
            field=models.BooleanField(blank=True, default=False, verbose_name='Убрать в архив'),
        ),
        migrations.AddField(
            model_name='executions',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='executions',
            name='court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courts.Courts', verbose_name='Суд'),
        ),
        migrations.AddField(
            model_name='executions',
            name='court_phone',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Контактный телефон'),
        ),
        migrations.AddField(
            model_name='executions',
            name='debt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма долга'),
        ),
        migrations.AddField(
            model_name='executions',
            name='exact',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма долга'),
        ),
        migrations.AddField(
            model_name='executions',
            name='executor',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='ФИО судебного пристава-исполнителя'),
        ),
        migrations.AddField(
            model_name='executions',
            name='observer',
            field=models.ManyToManyField(related_name='observer', to=settings.AUTH_USER_MODEL, verbose_name='Наблюдатель'),
        ),
        migrations.AddField(
            model_name='executions',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
        migrations.AddField(
            model_name='executions',
            name='text',
            field=models.TextField(default=' ', verbose_name='Дополнительная информация'),
        ),
    ]
