# Generated by Django 2.2.11 on 2020-07-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0003_auto_20200716_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='executions',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='executions',
            name='dispath_document',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='executions',
            name='document_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='executions',
            name='document_nmb',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='№ исполнительного листа'),
        ),
    ]
