# Generated by Django 2.2.11 on 2020-07-17 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('execution', '0004_auto_20200716_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_ducuments', models.FileField(upload_to='Executiondocuments/')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='execution.Executions', verbose_name='Исполнительное производство')),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_articles_ex', to='execution.Executions', verbose_name='Исполнительное производство')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария')),
            ],
        ),
    ]
