# Generated by Django 2.2.11 on 2020-07-28 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0005_executioncomments_executiondocuments'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ex_category', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='executions',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='execution.ExecutionCategory'),
        ),
    ]
