# Generated by Django 2.2.11 on 2020-08-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_connectionhistory'),
        ('execution', '0006_auto_20200728_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='executions',
            name='test',
            field=models.ManyToManyField(related_name='obr', to='profiles.Profiles', verbose_name='Наблюдатель'),
        ),
    ]
