# Generated by Django 3.0.7 on 2020-08-04 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0007_executions_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executions',
            name='test',
        ),
    ]
