# Generated by Django 3.1 on 2020-10-11 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0066_auto_20201011_1626'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('execution', '0008_remove_executions_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='executions',
            name='execution_count_model',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='executions',
            name='last_change_make_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_change_make_user+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HistoricalExecutions',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, editable=False, null=True)),
                ('dispath_document', models.DateField(blank=True, null=True)),
                ('arhive', models.BooleanField(blank=True, default=False, verbose_name='Убрать в архив')),
                ('document_nmb', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='№ исполнительного листа')),
                ('document_date', models.DateField(blank=True, null=True)),
                ('agency', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Наименование органа исполнения')),
                ('agency_address', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Адрес (местонахождение) органа исполнения')),
                ('agency_phone', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Контактный телефон')),
                ('debt', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма долга')),
                ('exact', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Взыскано')),
                ('executor', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='ФИО судебного пристава-исполнителя')),
                ('text', models.TextField(default=' ', verbose_name='Дополнительная информация')),
                ('execution_count_model', models.IntegerField(blank=True, default=None, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('category', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='execution.executioncategory')),
                ('court', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='courts.courts', verbose_name='Суд')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_change_make_user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'historical executions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
