# Generated by Django 3.1 on 2020-10-11 09:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('execution', '0009_auto_20201011_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='executions',
            name='read_execution_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='_executions_read_execution_users_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
