# Generated by Django 3.0.7 on 2020-06-23 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
