# Generated by Django 2.2.11 on 2020-07-07 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_auto_20200707_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supervisor',
            old_name='courtauthorvision',
            new_name='court_author_vision',
        ),
    ]
