# Generated by Django 2.2.11 on 2020-06-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courts',
            name='defeat_amount_additional',
        ),
        migrations.AddField(
            model_name='courts',
            name='actual_court_hearing',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Ближайшее судебное заседание'),
        ),
        migrations.AddField(
            model_name='courts',
            name='case_number',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='№ дела'),
        ),
        migrations.AddField(
            model_name='courts',
            name='court_address',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Адрес (местонахождение) суда'),
        ),
        migrations.AddField(
            model_name='courts',
            name='court_phone',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='№ телефона суда'),
        ),
        migrations.AddField(
            model_name='courts',
            name='date_getting_lawsuit',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата получения/подачи искового заявления'),
        ),
        migrations.AddField(
            model_name='courts',
            name='defeat_amount_expertize',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма экспертизы'),
        ),
        migrations.AddField(
            model_name='courts',
            name='defeat_amount_moral_damage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма морального/репутационного вреда'),
        ),
        migrations.AddField(
            model_name='courts',
            name='defeat_amount_penalty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма штрафа по ЗоЗПП'),
        ),
        migrations.AddField(
            model_name='courts',
            name='defeat_amount_penalty_agent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма неустойки'),
        ),
        migrations.AddField(
            model_name='courts',
            name='history_court_hearing',
            field=models.TextField(blank=True, default=None, max_length=200, null=True, verbose_name='История судебных заседаний по делу'),
        ),
        migrations.AddField(
            model_name='courts',
            name='win_amount_expertize',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма экспертизы'),
        ),
        migrations.AddField(
            model_name='courts',
            name='win_amount_moral_damage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма морального/репутационного вреда'),
        ),
        migrations.AddField(
            model_name='courts',
            name='win_amount_moral_damage_agent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма неустойки'),
        ),
    ]
