# Generated by Django 2.2.11 on 2020-06-15 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0002_auto_20200610_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtsJurisdiction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_instanse_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='courts',
            name='win_amount_additional',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма выигрыша / проигрыша по юр. услугам'),
        ),
        migrations.AddField(
            model_name='courts',
            name='jurisdiction',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='courts.CourtsJurisdiction'),
        ),
    ]
