# Generated by Django 2.2.11 on 2020-06-16 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0003_auto_20200615_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_instanse_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CourtsTypeProceedings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_instanse_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='courts',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='courts.CourtsCategory'),
        ),
        migrations.AddField(
            model_name='courts',
            name='type_proceedings',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='courts.CourtsTypeProceedings'),
        ),
    ]
