# Generated by Django 2.2.11 on 2020-06-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0004_auto_20200616_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='courts',
            name='arhive',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='Убрать в архив'),
        ),
    ]
