# Generated by Django 2.2.11 on 2020-06-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0005_courts_arhive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courts',
            name='arhive',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Убрать в архив'),
        ),
    ]
