# Generated by Django 2.2.11 on 2020-06-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0006_auto_20200616_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courts',
            name='arhive',
            field=models.BooleanField(blank=True, default=False, verbose_name='Убрать в архив'),
        ),
    ]
