# Generated by Django 2.2.11 on 2020-06-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0007_auto_20200616_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtsComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.TextField(verbose_name='подключить datetimefield')),
                ('user_name', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Пользователь')),
                ('comment_text', models.TextField(verbose_name='Текст комментария')),
            ],
        ),
    ]
