# Generated by Django 2.2.11 on 2020-06-17 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courts', '0009_auto_20200617_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courts',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='courtscomments',
            name='comment_text',
        ),
        migrations.RemoveField(
            model_name='courtscomments',
            name='user_name',
        ),
        migrations.AddField(
            model_name='courtscomments',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='courtscomments',
            name='court',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='courts.Courts', verbose_name='Судебное дело'),
        ),
        migrations.AddField(
            model_name='courtscomments',
            name='datetime',
            field=models.DateTimeField(null=True, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='courtscomments',
            name='text',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Текст'),
        ),
    ]
