# Generated by Django 2.2.11 on 2020-06-17 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('courts', '0010_auto_20200617_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courtscomments',
            name='court',
        ),
        migrations.RemoveField(
            model_name='courtscomments',
            name='datetime',
        ),
        migrations.AddField(
            model_name='courtscomments',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='courtscomments',
            name='created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='courtscomments',
            name='object_id',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='courtscomments',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='courtscomments',
            name='text',
            field=models.TextField(max_length=4096, null=True),
        ),
    ]
