# Generated by Django 3.0.7 on 2020-06-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0013_commentscourts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentscourts',
            name='create_date',
            field=models.DateTimeField(null=True),
        ),
    ]
