# Generated by Django 3.0.7 on 2020-06-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0015_auto_20200623_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentscourts',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
