# Generated by Django 2.2.11 on 2020-07-03 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0017_auto_20200625_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtsDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_ducuments', models.FileField(blank=True, null=True, upload_to='Courtdocuments/')),
            ],
        ),
        migrations.AddField(
            model_name='courts',
            name='court_documents',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='courts.CourtsDocuments'),
        ),
    ]
