# Generated by Django 2.2.11 on 2020-07-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0018_auto_20200703_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtsdocuments',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
