# Generated by Django 2.2.11 on 2020-07-03 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0020_auto_20200703_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courts',
            name='court_documents',
        ),
        migrations.DeleteModel(
            name='CourtsDocuments',
        ),
    ]
