# Generated by Django 2.2.11 on 2020-07-03 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0021_auto_20200703_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='123', max_length=200, null=True)),
                ('court_ducuments', models.FileField(blank=True, null=True, upload_to='Courtdocuments/')),
            ],
        ),
        migrations.AddField(
            model_name='courts',
            name='court_documents',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='courts.CourtDocuments'),
        ),
    ]
