# Generated by Django 2.2.11 on 2020-07-03 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('courts', '0023_auto_20200703_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courtdocuments',
            name='name',
        ),
        migrations.RemoveField(
            model_name='courts',
            name='court_documents',
        ),
        migrations.AddField(
            model_name='courtdocuments',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='courtdocuments',
            name='object_id',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
