# Generated by Django 2.2.11 on 2020-07-06 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0025_auto_20200703_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudicialDecision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judicial_decision', models.FileField(blank=True, null=True, upload_to='Courtdocuments/')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='courts.Courts', verbose_name='Судебное дело')),
            ],
        ),
    ]
