# Generated by Django 2.2.11 on 2020-07-06 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0026_judicialdecision'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JudicialDecision',
        ),
    ]
