# Generated by Django 2.2.11 on 2020-07-06 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0027_delete_judicialdecision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtdocuments',
            name='court_ducuments',
            field=models.FileField(upload_to='Courtdocuments/'),
        ),
    ]
