# Generated by Django 3.0.7 on 2020-07-11 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0031_auto_20200711_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courts',
            name='observer',
        ),
        migrations.AddField(
            model_name='courts',
            name='observer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courts.CourtsObservers', verbose_name='Ответственный'),
        ),
    ]
