# Generated by Django 3.0.7 on 2020-07-11 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courts', '0032_auto_20200711_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courtsobservers',
            name='observers',
        ),
        migrations.AddField(
            model_name='courtsobservers',
            name='observers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
    ]
