# Generated by Django 3.0.7 on 2020-07-11 10:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courts', '0033_auto_20200711_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courts',
            name='observer',
        ),
        migrations.AddField(
            model_name='courts',
            name='observer',
            field=models.ManyToManyField(blank=True, null=True, related_name='_courts_observer_+', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
        migrations.DeleteModel(
            name='CourtsObservers',
        ),
    ]
