# Generated by Django 3.0.7 on 2020-07-11 11:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courts', '0034_auto_20200711_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courts',
            name='observer',
            field=models.ManyToManyField(blank=True, null=True, related_name='obs', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
    ]
