# Generated by Django 2.2.11 on 2020-07-17 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0035_auto_20200711_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courtscomments',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='courtscomments',
            name='created',
        ),
        migrations.RemoveField(
            model_name='courtscomments',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='courtscomments',
            name='text',
        ),
    ]
