# Generated by Django 2.2.11 on 2020-07-17 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0036_auto_20200717_1629'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourtsComments',
        ),
    ]
