# Generated by Django 2.2.11 on 2020-08-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0038_auto_20200803_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='courts',
            name='arhive_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата перевода в архив'),
        ),
        migrations.AddField(
            model_name='courts',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
    ]
