# Generated by Django 2.2.11 on 2020-08-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0040_remove_courts_arhive_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='courts',
            name='arhive_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата перевода в архив'),
        ),
    ]
