# Generated by Django 3.1 on 2020-09-24 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0048_commentscourts_comment_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentscourts',
            name='comment_count',
        ),
    ]
