# Generated by Django 3.1 on 2020-09-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0049_remove_commentscourts_comment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='courts',
            name='court_comments_count',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
