# Generated by Django 3.1 on 2020-09-24 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0050_courts_court_comments_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courts',
            old_name='court_comments_count',
            new_name='court_comments_count_model',
        ),
    ]
