# Generated by Django 3.1 on 2020-09-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0051_auto_20200924_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courts',
            name='court_comments_count_model',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
