# Generated by Django 3.1 on 2020-09-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0052_auto_20200924_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courts',
            name='result_of_win',
            field=models.BooleanField(choices=[(None, 'I do not know now'), (True, 'Yes I acknowledge this'), (False, 'No, I do not like this')], null=True, verbose_name='Победа/Поражение'),
        ),
    ]
