# Generated by Django 3.1 on 2020-09-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0053_auto_20200924_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courts',
            name='court_comments_count_model',
        ),
        migrations.AlterField(
            model_name='courts',
            name='result_of_win',
            field=models.BooleanField(blank=True, choices=[(None, 'Решение суда отсутствует'), (True, 'Суд выйгран'), (False, 'Суд проигран')], null=True, verbose_name='Победа/Поражение'),
        ),
    ]
