# Generated by Django 3.1 on 2020-09-28 05:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courts', '0054_auto_20200928_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='courts',
            name='read_court_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='_courts_read_court_users_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
