# Generated by Django 3.1 on 2020-09-28 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0056_courts_comment_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courts',
            old_name='comment_count',
            new_name='comment_count_model',
        ),
    ]
