# Generated by Django 3.1 on 2020-09-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0057_auto_20200928_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='courts',
            name='history_of_change',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
