# Generated by Django 3.1 on 2020-09-30 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courts', '0059_remove_courts_history_of_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCourts',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, null=True, verbose_name='Дата создания')),
                ('arhive_date', models.DateField(blank=True, null=True, verbose_name='Дата перевода в архив')),
                ('arhive', models.BooleanField(blank=True, default=False, verbose_name='Убрать в архив')),
                ('court_name', models.CharField(max_length=200, verbose_name='Наименование суда')),
                ('case_number', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='№ дела')),
                ('date_getting_lawsuit', models.DateField(blank=True, default=None, null=True, verbose_name='Дата получения/подачи искового заявления')),
                ('court_address', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Адрес (местонахождение) суда')),
                ('court_phone', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='№ телефона суда')),
                ('plaintiff', models.CharField(max_length=200, verbose_name='Истец')),
                ('defendant', models.CharField(max_length=200, verbose_name='Ответчик')),
                ('lawsuit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма иска')),
                ('actual_court_hearing', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Ближайшее судебное заседание')),
                ('history_court_hearing', models.TextField(blank=True, default=None, max_length=200, null=True, verbose_name='История судебных заседаний по делу')),
                ('result_of_win', models.BooleanField(blank=True, choices=[(None, 'Решение суда отсутствует'), (True, 'Суд выйгран'), (False, 'Суд проигран')], null=True, verbose_name='Победа/Поражение')),
                ('win_amount_main', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма выигрыша по основному требованию')),
                ('win_amount_moral_damage_agent', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма неустойки')),
                ('win_amount_moral_damage', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма морального/репутационного вреда')),
                ('win_amount_expertize', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма экспертизы')),
                ('defeat_amount_main', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма проигрыша по основному требованию')),
                ('defeat_amount_penalty', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма штрафа по ЗоЗПП')),
                ('defeat_amount_penalty_agent', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма неустойки')),
                ('defeat_amount_moral_damage', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма морального/репутационного вреда')),
                ('defeat_amount_expertize', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма экспертизы')),
                ('win_amount_expected_additional', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма заявленная за юридические услуги')),
                ('win_amount_additional', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма выигрыша / проигрыша по юр. услугам')),
                ('text', models.TextField()),
                ('comment_count_model', models.IntegerField(blank=True, default=None, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('category', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='courts.courtscategory')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('instanse', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='courts.courtsinstanse')),
                ('jungment', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='courts.courtsjudgment')),
                ('jurisdiction', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='courts.courtsjurisdiction')),
                ('responsible', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('status', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='courts.courtsstatus')),
                ('type_proceedings', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='courts.courtstypeproceedings')),
            ],
            options={
                'verbose_name': 'historical courts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
