# Generated by Django 3.1 on 2020-09-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0060_historicalcourts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalcourts',
            name='history_change_reason',
            field=models.TextField(null=True),
        ),
    ]
