# Generated by Django 3.1 on 2020-10-01 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courts', '0061_auto_20200930_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='courts',
            name='last_change_make_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_change_make_user+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcourts',
            name='last_change_make_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
