# Generated by Django 3.1 on 2020-10-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0062_auto_20201001_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalcourts',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
