# Generated by Django 3.1 on 2020-10-06 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0063_auto_20201001_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='courts',
            name='court_history_count',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='historicalcourts',
            name='court_history_count',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='courts',
            name='text',
            field=models.TextField(verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='historicalcourts',
            name='text',
            field=models.TextField(verbose_name='Комментарий'),
        ),
    ]
