# Generated by Django 3.1 on 2020-10-06 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0064_auto_20201006_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courts',
            old_name='court_history_count',
            new_name='court_history_count_model',
        ),
        migrations.RenameField(
            model_name='historicalcourts',
            old_name='court_history_count',
            new_name='court_history_count_model',
        ),
    ]
