# Generated by Django 3.1 on 2020-10-11 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0065_auto_20201006_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courts',
            name='court_history_count_model',
        ),
        migrations.RemoveField(
            model_name='historicalcourts',
            name='court_history_count_model',
        ),
    ]
