# Generated by Django 3.1 on 2020-10-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0066_auto_20201011_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courts',
            old_name='result_of_win',
            new_name='court_result',
        ),
        migrations.RenameField(
            model_name='courts',
            old_name='defeat_amount_moral_damage',
            new_name='sum_amount_moral_damage',
        ),
        migrations.RenameField(
            model_name='courts',
            old_name='defeat_amount_penalty_agent',
            new_name='win_amount_penalty_agent',
        ),
        migrations.RenameField(
            model_name='historicalcourts',
            old_name='result_of_win',
            new_name='court_result',
        ),
        migrations.RenameField(
            model_name='historicalcourts',
            old_name='defeat_amount_moral_damage',
            new_name='sum_amount_moral_damage',
        ),
        migrations.RenameField(
            model_name='historicalcourts',
            old_name='defeat_amount_penalty_agent',
            new_name='win_amount_penalty_agent',
        ),
        migrations.RemoveField(
            model_name='courts',
            name='defeat_amount_expertize',
        ),
        migrations.RemoveField(
            model_name='courts',
            name='defeat_amount_main',
        ),
        migrations.RemoveField(
            model_name='courts',
            name='defeat_amount_penalty',
        ),
        migrations.RemoveField(
            model_name='courts',
            name='win_amount_main',
        ),
        migrations.RemoveField(
            model_name='courts',
            name='win_amount_moral_damage',
        ),
        migrations.RemoveField(
            model_name='courts',
            name='win_amount_moral_damage_agent',
        ),
        migrations.RemoveField(
            model_name='historicalcourts',
            name='defeat_amount_expertize',
        ),
        migrations.RemoveField(
            model_name='historicalcourts',
            name='defeat_amount_main',
        ),
        migrations.RemoveField(
            model_name='historicalcourts',
            name='defeat_amount_penalty',
        ),
        migrations.RemoveField(
            model_name='historicalcourts',
            name='win_amount_main',
        ),
        migrations.RemoveField(
            model_name='historicalcourts',
            name='win_amount_moral_damage',
        ),
        migrations.RemoveField(
            model_name='historicalcourts',
            name='win_amount_moral_damage_agent',
        ),
        migrations.AddField(
            model_name='courts',
            name='sum_amount_main',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма по основному требованию'),
        ),
        migrations.AddField(
            model_name='historicalcourts',
            name='sum_amount_main',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма по основному требованию'),
        ),
        migrations.AlterField(
            model_name='courts',
            name='actual_court_hearing',
            field=models.DateTimeField(blank=True, default=None, max_length=200, null=True, verbose_name='Ближайшее судебное заседание'),
        ),
        migrations.AlterField(
            model_name='courts',
            name='court_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Наименование суда'),
        ),
        migrations.AlterField(
            model_name='historicalcourts',
            name='actual_court_hearing',
            field=models.DateTimeField(blank=True, default=None, max_length=200, null=True, verbose_name='Ближайшее судебное заседание'),
        ),
        migrations.AlterField(
            model_name='historicalcourts',
            name='court_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Наименование суда'),
        ),
    ]
