# Generated by Django 3.1 on 2020-11-02 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0069_auto_20201102_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='courts',
            name='sum_amount_main_prognosis',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма по основному требованию (заявленная)'),
        ),
        migrations.AddField(
            model_name='courts',
            name='sum_amount_moral_damage_prognosis',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма морального/репутационного вреда (заявленая)'),
        ),
        migrations.AddField(
            model_name='courts',
            name='sum_amount_penalty_agent_prognosis',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма неустойки (заявленная)'),
        ),
        migrations.AddField(
            model_name='courts',
            name='sum_of_penalty_prognosis',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма штрафа (прогнозируемая)'),
        ),
        migrations.AddField(
            model_name='historicalcourts',
            name='sum_amount_main_prognosis',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма по основному требованию (заявленная)'),
        ),
        migrations.AddField(
            model_name='historicalcourts',
            name='sum_amount_moral_damage_prognosis',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма морального/репутационного вреда (заявленая)'),
        ),
        migrations.AddField(
            model_name='historicalcourts',
            name='sum_amount_penalty_agent_prognosis',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма неустойки (заявленная)'),
        ),
        migrations.AddField(
            model_name='historicalcourts',
            name='sum_of_penalty_prognosis',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма штрафа (прогнозируемая)'),
        ),
        migrations.AlterField(
            model_name='courts',
            name='sum_amount_main',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма по основному требованию (фактически)'),
        ),
        migrations.AlterField(
            model_name='courts',
            name='sum_amount_moral_damage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма морального/репутационного вреда (фактически)'),
        ),
        migrations.AlterField(
            model_name='courts',
            name='sum_amount_penalty_agent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма неустойки (фактически)'),
        ),
        migrations.AlterField(
            model_name='courts',
            name='sum_of_penalty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма штрафа (фактически)'),
        ),
        migrations.AlterField(
            model_name='historicalcourts',
            name='sum_amount_main',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма по основному требованию (фактически)'),
        ),
        migrations.AlterField(
            model_name='historicalcourts',
            name='sum_amount_moral_damage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма морального/репутационного вреда (фактически)'),
        ),
        migrations.AlterField(
            model_name='historicalcourts',
            name='sum_amount_penalty_agent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма неустойки (фактически)'),
        ),
        migrations.AlterField(
            model_name='historicalcourts',
            name='sum_of_penalty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма штрафа (фактически)'),
        ),
    ]
