# Generated by Django 3.1 on 2020-11-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0070_auto_20201102_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='courts',
            name='defendant_peresentative',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Ответчик'),
        ),
        migrations.AddField(
            model_name='courts',
            name='plaintiff_peresentative',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Истец'),
        ),
        migrations.AddField(
            model_name='historicalcourts',
            name='defendant_peresentative',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Ответчик'),
        ),
        migrations.AddField(
            model_name='historicalcourts',
            name='plaintiff_peresentative',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Истец'),
        ),
    ]
