# Generated by Django 3.1 on 2020-11-02 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0072_auto_20201102_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courts',
            old_name='defendant_peresentative',
            new_name='defendant_representative',
        ),
        migrations.RenameField(
            model_name='courts',
            old_name='plaintiff_peresentative',
            new_name='plaintiff_representative',
        ),
        migrations.RenameField(
            model_name='historicalcourts',
            old_name='defendant_peresentative',
            new_name='defendant_representative',
        ),
        migrations.RenameField(
            model_name='historicalcourts',
            old_name='plaintiff_peresentative',
            new_name='plaintiff_representative',
        ),
    ]
