# Generated by Django 3.1 on 2020-11-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0075_remove_commentscourts_text_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='courts',
            name='type_proceedings_choises',
            field=models.CharField(blank=True, choices=[('Первое', 'Гражданское судопроизводство'), ('Второе', 'Уголовное судопроизводство'), ('Третье', 'Административное судопроизводство')], default=None, max_length=200, null=True, verbose_name='Вид судопроизводства'),
        ),
        migrations.AddField(
            model_name='historicalcourts',
            name='type_proceedings_choises',
            field=models.CharField(blank=True, choices=[('Первое', 'Гражданское судопроизводство'), ('Второе', 'Уголовное судопроизводство'), ('Третье', 'Административное судопроизводство')], default=None, max_length=200, null=True, verbose_name='Вид судопроизводства'),
        ),
    ]
