# Generated by Django 3.1 on 2020-11-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0076_auto_20201102_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courts',
            name='type_proceedings_choises',
            field=models.BooleanField(blank=True, choices=[(None, 'Гражданское судопроизводство'), (True, 'Уголовное судопроизводство'), (False, 'Административное судопроизводство')], default=None, null=True, verbose_name='Вид судопроизводства'),
        ),
        migrations.AlterField(
            model_name='historicalcourts',
            name='type_proceedings_choises',
            field=models.BooleanField(blank=True, choices=[(None, 'Гражданское судопроизводство'), (True, 'Уголовное судопроизводство'), (False, 'Административное судопроизводство')], default=None, null=True, verbose_name='Вид судопроизводства'),
        ),
    ]
