# Generated by Django 3.1 on 2020-11-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0078_auto_20201102_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courts',
            name='type_proceedings',
        ),
        migrations.RemoveField(
            model_name='historicalcourts',
            name='type_proceedings',
        ),
        migrations.AlterField(
            model_name='courts',
            name='type_proceedings_choises',
            field=models.CharField(blank=True, choices=[('Гражданское судопроизводство', 'Гражданское судопроизводство'), ('Уголовное судопроизводство', 'Уголовное судопроизводство'), ('Уголовное судопроизводство', 'Административное судопроизводство')], default=None, max_length=200, null=True, verbose_name='Вид судопроизводства'),
        ),
        migrations.AlterField(
            model_name='historicalcourts',
            name='type_proceedings_choises',
            field=models.CharField(blank=True, choices=[('Гражданское судопроизводство', 'Гражданское судопроизводство'), ('Уголовное судопроизводство', 'Уголовное судопроизводство'), ('Уголовное судопроизводство', 'Административное судопроизводство')], default=None, max_length=200, null=True, verbose_name='Вид судопроизводства'),
        ),
        migrations.DeleteModel(
            name='CourtsTypeProceedings',
        ),
    ]
