# Generated by Django 3.1 on 2020-11-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0079_auto_20201102_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courts',
            name='type_proceedings_choises',
            field=models.IntegerField(blank=True, choices=[('Сivil', 'Гражданское судопроизводство'), ('Criminal', 'Уголовное судопроизводство'), ('Administrical', 'Административное судопроизводство')], default=None, null=True, verbose_name='Вид судопроизводства'),
        ),
        migrations.AlterField(
            model_name='historicalcourts',
            name='type_proceedings_choises',
            field=models.IntegerField(blank=True, choices=[('Сivil', 'Гражданское судопроизводство'), ('Criminal', 'Уголовное судопроизводство'), ('Administrical', 'Административное судопроизводство')], default=None, null=True, verbose_name='Вид судопроизводства'),
        ),
    ]
