# Generated by Django 3.1 on 2020-11-03 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0080_auto_20201102_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courts',
            name='defendant',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ответчик'),
        ),
        migrations.AlterField(
            model_name='courts',
            name='plaintiff',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Истец'),
        ),
        migrations.AlterField(
            model_name='courts',
            name='sum_amount_additional',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Сумма выигрыша / проигрыша по юр. услугам'),
        ),
        migrations.AlterField(
            model_name='courts',
            name='sum_amount_expected_additional',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Сумма заявленная за юридические услуги'),
        ),
        migrations.AlterField(
            model_name='courts',
            name='sum_amount_expertize',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Сумма экспертизы'),
        ),
        migrations.AlterField(
            model_name='courts',
            name='sum_amount_main',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Сумма по основному требованию (фактически)'),
        ),
        migrations.AlterField(
            model_name='courts',
            name='sum_amount_main_prognosis',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Сумма по основному требованию (заявленная)'),
        ),
        migrations.AlterField(
            model_name='courts',
            name='sum_amount_moral_damage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Сумма морального/репутационного вреда (фактически)'),
        ),
        migrations.AlterField(
            model_name='courts',
            name='sum_amount_moral_damage_prognosis',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Сумма морального/репутационного вреда (заявленая)'),
        ),
        migrations.AlterField(
            model_name='courts',
            name='sum_amount_penalty_agent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Сумма неустойки (фактически)'),
        ),
        migrations.AlterField(
            model_name='courts',
            name='sum_amount_penalty_agent_prognosis',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Сумма неустойки (заявленная)'),
        ),
        migrations.AlterField(
            model_name='courts',
            name='sum_of_penalty',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Сумма штрафа (фактически)'),
        ),
        migrations.AlterField(
            model_name='courts',
            name='sum_of_penalty_prognosis',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Сумма штрафа (прогнозируемая)'),
        ),
        migrations.AlterField(
            model_name='courts',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='courts',
            name='type_proceedings_choises',
            field=models.IntegerField(blank=True, choices=[(1, 'Гражданское судопроизводство'), (2, 'Уголовное судопроизводство'), (3, 'Административное судопроизводство')], default=None, null=True, verbose_name='Вид судопроизводства'),
        ),
        migrations.AlterField(
            model_name='historicalcourts',
            name='defendant',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ответчик'),
        ),
        migrations.AlterField(
            model_name='historicalcourts',
            name='plaintiff',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Истец'),
        ),
        migrations.AlterField(
            model_name='historicalcourts',
            name='sum_amount_additional',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Сумма выигрыша / проигрыша по юр. услугам'),
        ),
        migrations.AlterField(
            model_name='historicalcourts',
            name='sum_amount_expected_additional',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Сумма заявленная за юридические услуги'),
        ),
        migrations.AlterField(
            model_name='historicalcourts',
            name='sum_amount_expertize',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Сумма экспертизы'),
        ),
        migrations.AlterField(
            model_name='historicalcourts',
            name='sum_amount_main',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Сумма по основному требованию (фактически)'),
        ),
        migrations.AlterField(
            model_name='historicalcourts',
            name='sum_amount_main_prognosis',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Сумма по основному требованию (заявленная)'),
        ),
        migrations.AlterField(
            model_name='historicalcourts',
            name='sum_amount_moral_damage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Сумма морального/репутационного вреда (фактически)'),
        ),
        migrations.AlterField(
            model_name='historicalcourts',
            name='sum_amount_moral_damage_prognosis',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Сумма морального/репутационного вреда (заявленая)'),
        ),
        migrations.AlterField(
            model_name='historicalcourts',
            name='sum_amount_penalty_agent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Сумма неустойки (фактически)'),
        ),
        migrations.AlterField(
            model_name='historicalcourts',
            name='sum_amount_penalty_agent_prognosis',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Сумма неустойки (заявленная)'),
        ),
        migrations.AlterField(
            model_name='historicalcourts',
            name='sum_of_penalty',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Сумма штрафа (фактически)'),
        ),
        migrations.AlterField(
            model_name='historicalcourts',
            name='sum_of_penalty_prognosis',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Сумма штрафа (прогнозируемая)'),
        ),
        migrations.AlterField(
            model_name='historicalcourts',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='historicalcourts',
            name='type_proceedings_choises',
            field=models.IntegerField(blank=True, choices=[(1, 'Гражданское судопроизводство'), (2, 'Уголовное судопроизводство'), (3, 'Административное судопроизводство')], default=None, null=True, verbose_name='Вид судопроизводства'),
        ),
    ]
