# Generated by Django 3.1 on 2020-11-03 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0081_auto_20201103_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='courts',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='Готовый экземпляр судебного дела'),
        ),
        migrations.AddField(
            model_name='historicalcourts',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='Готовый экземпляр судебного дела'),
        ),
    ]
