# Generated by Django 3.1 on 2020-11-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0084_auto_20201103_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courts',
            name='type_proceedings_choises',
            field=models.IntegerField(blank=True, choices=[(1, 'Гражданское судопроизводство'), (2, 'Уголовное судопроизводство'), (3, 'Административное судопроизводство')], default=None, null=True, verbose_name='Вид судопроизводства'),
        ),
        migrations.AlterField(
            model_name='historicalcourts',
            name='type_proceedings_choises',
            field=models.IntegerField(blank=True, choices=[(1, 'Гражданское судопроизводство'), (2, 'Уголовное судопроизводство'), (3, 'Административное судопроизводство')], default=None, null=True, verbose_name='Вид судопроизводства'),
        ),
    ]
