# Generated by Django 3.1 on 2020-11-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0089_auto_20201103_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courts',
            name='defendant',
            field=models.CharField(max_length=200, verbose_name='Ответчик'),
        ),
        migrations.AlterField(
            model_name='courts',
            name='plaintiff',
            field=models.CharField(max_length=200, verbose_name='Истец'),
        ),
        migrations.AlterField(
            model_name='historicalcourts',
            name='defendant',
            field=models.CharField(max_length=200, verbose_name='Ответчик'),
        ),
        migrations.AlterField(
            model_name='historicalcourts',
            name='plaintiff',
            field=models.CharField(max_length=200, verbose_name='Истец'),
        ),
    ]
