# Generated by Django 3.1 on 2020-11-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0092_auto_20201103_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='courts',
            name='state_duty',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Сумма госпошлины'),
        ),
        migrations.AddField(
            model_name='historicalcourts',
            name='state_duty',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Сумма госпошлины'),
        ),
    ]
