# Generated by Django 3.1 on 2020-11-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0093_auto_20201105_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='courts',
            name='fare_expected_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Сумма заявленная за транспортные расходы'),
        ),
        migrations.AddField(
            model_name='courts',
            name='fare_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Сумма присужденная за транспортные расходы'),
        ),
        migrations.AddField(
            model_name='courts',
            name='other_expected_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Иные заявленные расходы'),
        ),
        migrations.AddField(
            model_name='courts',
            name='other_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Иные присужденные расходы'),
        ),
        migrations.AddField(
            model_name='courts',
            name='postage_expected_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Сумма заявленная за почтовые расходы'),
        ),
        migrations.AddField(
            model_name='courts',
            name='postage_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Сумма взыскананная за почтовые расходы'),
        ),
        migrations.AddField(
            model_name='courts',
            name='total_amount_additional',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Сумма взысканная за юр. услуги ОБЩАЯ'),
        ),
        migrations.AddField(
            model_name='courts',
            name='total_amount_expected_additional',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Сумма заявленная за юридические услуги ОБЩАЯ'),
        ),
        migrations.AddField(
            model_name='historicalcourts',
            name='fare_expected_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Сумма заявленная за транспортные расходы'),
        ),
        migrations.AddField(
            model_name='historicalcourts',
            name='fare_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Сумма присужденная за транспортные расходы'),
        ),
        migrations.AddField(
            model_name='historicalcourts',
            name='other_expected_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Иные заявленные расходы'),
        ),
        migrations.AddField(
            model_name='historicalcourts',
            name='other_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Иные присужденные расходы'),
        ),
        migrations.AddField(
            model_name='historicalcourts',
            name='postage_expected_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Сумма заявленная за почтовые расходы'),
        ),
        migrations.AddField(
            model_name='historicalcourts',
            name='postage_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Сумма взыскананная за почтовые расходы'),
        ),
        migrations.AddField(
            model_name='historicalcourts',
            name='total_amount_additional',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Сумма взысканная за юр. услуги ОБЩАЯ'),
        ),
        migrations.AddField(
            model_name='historicalcourts',
            name='total_amount_expected_additional',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Сумма заявленная за юридические услуги ОБЩАЯ'),
        ),
        migrations.AlterField(
            model_name='courts',
            name='sum_amount_additional',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Сумма взысканная за юр услуги'),
        ),
        migrations.AlterField(
            model_name='historicalcourts',
            name='sum_amount_additional',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Сумма взысканная за юр услуги'),
        ),
    ]
