# Generated by Django 3.1 on 2020-11-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0096_auto_20201105_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courts',
            name='court_result',
            field=models.BooleanField(choices=[(1, 'Решение суда отсутствует'), (2, 'Суд выйгран'), (3, 'Суд проигран')], default=1, verbose_name='Победа/Поражение'),
        ),
        migrations.AlterField(
            model_name='historicalcourts',
            name='court_result',
            field=models.BooleanField(choices=[(1, 'Решение суда отсутствует'), (2, 'Суд выйгран'), (3, 'Суд проигран')], default=1, verbose_name='Победа/Поражение'),
        ),
    ]
