# Generated by Django 3.1 on 2020-11-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0097_auto_20201109_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='courts',
            name='type_of_decision_civil',
            field=models.IntegerField(choices=[(0, 'Решение судом не принято'), (1, 'Удовлетворение требований Истца в полном объеме'), (2, 'Частичное удовлетворение требований Истца'), (3, 'Отказ в удовлетворении требований'), (4, 'Отказ в принятии искового заявления'), (5, 'Оставление искового заявления без движения'), (6, 'Возвращение искового заявления')], default=0, verbose_name=''),
        ),
        migrations.AddField(
            model_name='courts',
            name='type_of_decision_criminal',
            field=models.IntegerField(choices=[(0, 'Приговор не вынесен'), (1, 'Обвинительный приговор'), (2, 'Оправдательный приговор')], default=0, verbose_name=''),
        ),
        migrations.AddField(
            model_name='historicalcourts',
            name='type_of_decision_civil',
            field=models.IntegerField(choices=[(0, 'Решение судом не принято'), (1, 'Удовлетворение требований Истца в полном объеме'), (2, 'Частичное удовлетворение требований Истца'), (3, 'Отказ в удовлетворении требований'), (4, 'Отказ в принятии искового заявления'), (5, 'Оставление искового заявления без движения'), (6, 'Возвращение искового заявления')], default=0, verbose_name=''),
        ),
        migrations.AddField(
            model_name='historicalcourts',
            name='type_of_decision_criminal',
            field=models.IntegerField(choices=[(0, 'Приговор не вынесен'), (1, 'Обвинительный приговор'), (2, 'Оправдательный приговор')], default=0, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='courts',
            name='type_proceedings_choises',
            field=models.IntegerField(choices=[(1, 'Гражданское судопроизводство'), (2, 'Уголовное судопроизводство'), (3, 'Административное судопроизводство'), (4, 'Производство по делам об адмп. правонарушении')], verbose_name='Вид судопроизводства'),
        ),
        migrations.AlterField(
            model_name='historicalcourts',
            name='type_proceedings_choises',
            field=models.IntegerField(choices=[(1, 'Гражданское судопроизводство'), (2, 'Уголовное судопроизводство'), (3, 'Административное судопроизводство'), (4, 'Производство по делам об адмп. правонарушении')], verbose_name='Вид судопроизводства'),
        ),
    ]
