# Generated by Django 3.1 on 2020-11-09 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0100_auto_20201109_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courts',
            name='court_result',
            field=models.IntegerField(choices=[(1, 'Решение суда отсутствует'), (2, 'Решение суда вынесено в нашу пользу'), (3, 'Решение суда вынесено не в нашу пользу')], default=1, verbose_name='Победа/Поражение'),
        ),
        migrations.AlterField(
            model_name='historicalcourts',
            name='court_result',
            field=models.IntegerField(choices=[(1, 'Решение суда отсутствует'), (2, 'Решение суда вынесено в нашу пользу'), (3, 'Решение суда вынесено не в нашу пользу')], default=1, verbose_name='Победа/Поражение'),
        ),
    ]
