# Generated by Django 3.1 on 2020-11-09 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0102_auto_20201109_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courts',
            name='court_result',
            field=models.IntegerField(choices=[(None, 'Решение суда отсутствует'), (1, 'Решение суда вынесено в нашу пользу'), (2, 'Решение суда вынесено не в нашу пользу')], default=None, verbose_name='Победа/Поражение'),
        ),
        migrations.AlterField(
            model_name='courts',
            name='total_sum_in_the_case',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Общая присужденная сумма по делу'),
        ),
        migrations.AlterField(
            model_name='courts',
            name='total_sum_in_the_case_prognosis',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Общая заявленная сумма по делу'),
        ),
        migrations.AlterField(
            model_name='historicalcourts',
            name='court_result',
            field=models.IntegerField(choices=[(None, 'Решение суда отсутствует'), (1, 'Решение суда вынесено в нашу пользу'), (2, 'Решение суда вынесено не в нашу пользу')], default=None, verbose_name='Победа/Поражение'),
        ),
        migrations.AlterField(
            model_name='historicalcourts',
            name='total_sum_in_the_case',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Общая присужденная сумма по делу'),
        ),
        migrations.AlterField(
            model_name='historicalcourts',
            name='total_sum_in_the_case_prognosis',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Общая заявленная сумма по делу'),
        ),
    ]
