# Generated by Django 3.1 on 2020-11-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0104_auto_20201109_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courts',
            old_name='instanse',
            new_name='instance',
        ),
        migrations.RemoveField(
            model_name='historicalcourts',
            name='instanse',
        ),
        migrations.AlterField(
            model_name='courts',
            name='type_of_decision_civil',
            field=models.IntegerField(blank=True, choices=[(1, 'Удовлетворение требований Истца в полном объеме'), (2, 'Частичное удовлетворение требований Истца'), (3, 'Отказ в удовлетворении требований'), (4, 'Отказ в принятии искового заявления'), (5, 'Оставление искового заявления без движения'), (6, 'Возвращение искового заявления')], default=None, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='historicalcourts',
            name='type_of_decision_civil',
            field=models.IntegerField(blank=True, choices=[(1, 'Удовлетворение требований Истца в полном объеме'), (2, 'Частичное удовлетворение требований Истца'), (3, 'Отказ в удовлетворении требований'), (4, 'Отказ в принятии искового заявления'), (5, 'Оставление искового заявления без движения'), (6, 'Возвращение искового заявления')], default=None, null=True, verbose_name=''),
        ),
    ]
