# Generated by Django 3.1 on 2020-11-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0105_auto_20201109_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courts',
            name='instance',
            field=models.IntegerField(blank=True, choices=[(1, 'Первая инстанция'), (2, 'Апелляционная инстанция'), (3, 'Кассационная инстанция'), (4, 'Надзорная инстанция')], default=None, null=True, verbose_name='Судебная инстанция'),
        ),
    ]
