# Generated by Django 3.1 on 2020-11-09 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0106_auto_20201109_1425'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalCourts',
        ),
    ]
