# Generated by Django 3.1 on 2020-11-09 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0107_delete_historicalcourts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourtsInstanse',
        ),
    ]
