# Generated by Django 3.1 on 2020-11-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0108_delete_courtsinstanse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courts',
            name='date_getting_lawsuit',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата получения/подачи искового заявления (возбуждения уголовного дела)'),
        ),
        migrations.AlterField(
            model_name='courts',
            name='defendant',
            field=models.CharField(max_length=200, verbose_name='Ответчик / Подсудимый'),
        ),
        migrations.AlterField(
            model_name='courts',
            name='defendant_representative',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Представитель ответчика / Подсудимого'),
        ),
        migrations.AlterField(
            model_name='courts',
            name='jurisdiction',
            field=models.IntegerField(blank=True, choices=[(1, 'Суды общей юрисдикции'), (2, 'Арбитражные суды'), (3, 'Третейские суды')], default=None, null=True, verbose_name='Подведомственность (Юрисдикция)'),
        ),
        migrations.AlterField(
            model_name='courts',
            name='plaintiff',
            field=models.CharField(max_length=200, verbose_name='Истец / Потерпевший'),
        ),
        migrations.AlterField(
            model_name='courts',
            name='plaintiff_representative',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Представитель Истца / Потерпевшего'),
        ),
    ]
