# Generated by Django 3.1 on 2020-11-09 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0109_auto_20201109_1500'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourtsJurisdiction',
        ),
    ]
