# Generated by Django 3.1 on 2020-11-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0110_delete_courtsjurisdiction'),
    ]

    operations = [
        migrations.AddField(
            model_name='courts',
            name='date_of_judgment',
            field=models.DateField(blank=True, null=True, verbose_name='Дата вынесения судебного решения'),
        ),
    ]
